### ISSUE TITLE
Garland - text overflow

### ISSUE THREAD

**Issue by Mates-K1** [sbillard/ZenPhoto20-DEV#7]
![ffb0e463-6c89-485f-9320-1a2a137c6174](https://user-images.githubusercontent.com/7648991/39894475-44b8200c-54a7-11e8-8d5c-0c2967f41fda.jpg)

**Comment by Mates-K1** [comment]
New in DEV.

**Comment by sbillard** [comment]
This problem also exists in the base release. The lines do not break because there is no "breaking" character in the title. One presumes that this happened because there album (or image) filename was used directly for the title. 

There is not really a good "fix" for this. It is hard to "predict" at what point in the title the overflow will occur. Possibly we could insert a breaking hyphen at regular intervals, but I doubt that would end up looking much better. 

No one has reported this before (and this theme has been around pretty much since the beginning of the legacy zenphoto code.) I suspect that the site owners simply made a title that either did not overflow or that had spaces and other beraking characters in it.

So, for now we will not fix this.
